Repository team-monew/Monew, pull requests merged in 2025-09, with the labels that each got.

#4 🔧 chore : 프로젝트 초기 셋팅 (husky, tailwindcss)
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/index.css
  src/main.tsx
  vite.config.ts
Labels: Type: Setting ⚙

#6 🎨 setting : 이미지, 아이콘 추가 및 pr 템플릿 변경
  .github/PULL_REQUEST_TEMPLATE.md
  src/assets/icons/add.svg
  src/assets/icons/bell.svg
  src/assets/icons/check-default.svg
  src/assets/icons/check-hover.svg
  src/assets/icons/chevron-down-16.svg
  src/assets/icons/chevron-down-24.svg
  src/assets/icons/chevron-left.svg
  src/assets/icons/chevron-right.svg
  src/assets/icons/close-primary-24.svg
  src/assets/icons/close-secondary-24.svg
  src/assets/icons/close-tertiary-12.svg
  src/assets/icons/comment.svg
  src/assets/icons/edit.svg
  src/assets/icons/error.svg
  src/assets/icons/filter-ascending.svg
  src/assets/icons/filter-descending.svg
  src/assets/icons/kebab-menu-20.svg
  src/assets/icons/kebab-menu-32.svg
  src/assets/icons/like-active.svg
  src/assets/icons/like-default.svg
  src/assets/icons/notification-default.svg
  src/assets/icons/notification-unread.svg
  src/assets/icons/plus.svg
  src/assets/icons/search.svg
  src/assets/icons/subdirectory.svg
  src/assets/icons/success.svg
  src/assets/icons/user.svg
  src/assets/images/chosun-ilbo.svg
  src/assets/images/empty.svg
  src/assets/images/korean-economy.svg
  src/assets/images/logo.svg
  src/assets/images/naver.svg
  src/assets/images/symbol.svg
  src/assets/images/yonhap-news.svg
Labels: Type: Setting ⚙

#12 ✨ feat : 드롭다운 공용 컴포넌트 구현
  src/components/common/Footer.tsx
  src/components/common/gnb/HeaderTabButton.tsx
  src/components/common/gnb/HeaderTabs.tsx
  src/components/common/gnb/HeaderUserMenu.tsx
  src/components/common/gnb/Logo.tsx
  src/components/common/gnb/PrivateHeader.tsx
  src/components/common/gnb/PublicHeader.tsx
  src/components/common/gnb/headerStyle.ts
  src/components/common/gnb/index.ts
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownItem.tsx
  src/components/dropdown/index.ts
  src/components/gnb/index.ts
  src/components/searchBar.tsx
  src/layouts/PrivateLayout.tsx
  src/layouts/PublicLayout.tsx
Labels: Type: Feature ✨, Type: Html&css 🎨

#21 :sparkles: feat : API DTO 정의 및 API 함수 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/articles/index.ts
  src/api/articles/types.ts
  src/api/comments/index.ts
  src/api/comments/types.ts
  src/api/interests/index.ts
  src/api/interests/types.ts
  src/api/notifications/index.ts
  src/api/notifications/types.ts
  src/api/user-activities/index.ts
  src/api/user-activities/types.ts
  src/api/users/index.ts
  src/api/users/types.ts
  src/components/common/gnb/HeaderTabButton.tsx
  src/components/common/gnb/HeaderTabs.tsx
  src/lib/http.ts
  src/pages/activities/ActivitiesPage.tsx
  src/pages/activities/components/.gitkeep
  src/pages/articles/ArticlesPage.tsx
  src/pages/articles/components/.gitkeep
  src/pages/feed/ArticlesPage.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/history/HistoryPage.tsx
  src/pages/history/components/.gitkeep
  src/pages/test/TestPage.tsx
  src/shared/constants/routes.ts
  src/types/direction.ts
  src/types/ids.ts
  vite.config.ts
Labels: Type: API 📬, Type: Feature ✨, Type: Setting ⚙

#23 :sparkles: feat : 공용 컴포넌트 modal 구현
  src/api/articles/index.ts
  src/api/comments/index.ts
  src/api/interests/index.ts
  src/api/notifications/index.ts
  src/api/users/index.ts
  src/components/modal/ArticleModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/ModalLayout.tsx
  src/components/modal/UpdateModal.tsx
  src/lib/http.ts
  src/shared/hooks/useArticleRecoveryModal.ts
  src/shared/hooks/useEditModal.ts
  src/shared/hooks/useUpdateModal.ts
Labels: Type: Feature ✨, Type: Html&css 🎨

#26 ✨ feat : Login 페이지 구현 / user 상태 관리 파일 추가
  src/components/Input.tsx
  src/components/common/gnb/HeaderLogOutButton.tsx
  src/components/common/gnb/HeaderUserMenu.tsx
  src/components/common/gnb/Logo.tsx
  src/components/common/gnb/PrivateHeader.tsx
  src/components/common/gnb/PublicHeader.tsx
  src/layouts/PublicLayout.tsx
  src/pages/auth/login/LoginPage.tsx
  src/pages/auth/login/components/.gitkeep
  src/pages/auth/login/components/LoginForm.tsx
  src/shared/auth/actions.ts
  src/shared/auth/authSession.ts
  src/shared/auth/useAuth.ts
  src/shared/auth/useAuthInfo.ts
  src/shared/constants/events.ts
  src/shared/store/.gitkeep
  src/shared/utils/inputValidation.ts
Labels: Type: Feature ✨, Type: Html&css 🎨

#29 :wrench: setting : 폴더 구조 재설정 - 기능별 분류(features)
  src/App.tsx
  src/api/articles/index.ts
  src/api/comments/index.ts
  src/api/interests/index.ts
  src/api/notifications/index.ts
  src/api/user-activities/index.ts
  src/api/users/index.ts
  src/components/EmptyState.tsx
  src/components/Footer.tsx
  src/components/Toast.tsx
  src/components/button/Button.tsx
  src/components/button/button.styles.ts
  src/components/common/gnb/index.ts
  src/components/gnb/HeaderLogOutButton.tsx
  src/components/gnb/HeaderTabButton.tsx
  src/components/gnb/HeaderTabs.tsx
  src/components/gnb/HeaderUserMenu.tsx
  src/components/gnb/Logo.tsx
  src/components/gnb/PrivateHeader.tsx
  src/components/gnb/PublicHeader.tsx
  src/components/gnb/header.styles.ts
  src/components/gnb/index.ts
  src/components/modal/ArticleModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/ModalLayout.tsx
  src/components/modal/UpdateModal.tsx
  src/features/activities/components/.gitkeep
  src/features/articles/components/.gitkeep
  src/features/auth/actions.ts
  src/features/auth/components/LoginForm.tsx
  src/features/auth/hooks/useAuth.ts
  src/features/auth/hooks/useAuthInfo.ts
  src/features/auth/utils/authSession.ts
  src/features/comments/components/Comment.tsx
  src/features/comments/components/CommentHistory.tsx
  src/features/interests/components/Interest.tsx
  src/features/notifications/.gitkeep
  src/layouts/PrivateLayout.tsx
  src/layouts/PublicLayout.tsx
  src/main.tsx
  src/pages/ActivitiesPage.tsx
  src/pages/ArticlesPage.tsx
  src/pages/InterestsPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/TestPage.tsx
  src/pages/auth/signup/components/.gitkeep
  src/pages/landing/components/LandingBox.tsx
  src/shared/lib/http.ts
  tsconfig.app.json
Labels: Type: Setting ⚙
