Repository team-monew/Monew, pull requests merged in 2025-10, with the labels that each got.

#41 :memo: docs : README 작성
  README.md
Labels: Type: Docs 📃

#43 :memo: docs : README.md 내용 수정
  README.md
Labels: Type: Docs 📃

#51 🚀 deploy : dev -> main 병합
  src/app/routes/private/ArticlesPage.tsx
  src/shared/components/modal/ArticleDetailModal.tsx
  src/shared/components/modal/ModalLayout.tsx
Labels: Type: Deploy 🌏

#54 chore: 레이아웃 중복 overflow-auto 코드 제거
  src/app/layouts/PrivateLayout.tsx
Labels: Type: Refactor ♻️

#58 :art: design(activities): 텍스트 개별 반응형 디자인 제거
  src/features/activities/components/ActivitiesTabs.tsx
  src/features/user/components/ProfileCard.tsx
Labels: Type: Html&css 🎨

#59 🚀 Deploy : dev -> main 병합
  src/features/activities/components/ActivitiesTabs.tsx
  src/features/user/components/ProfileCard.tsx
Labels: Type: Html&css 🎨
